#!/bin/bash
echo "🔧 Configuration de Xcode"
echo ""
echo "Pour configurer Xcode, exécutez ces commandes dans le terminal:"
echo ""
echo "1. Configurer le chemin Xcode:"
echo "   sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer"
echo ""
echo "2. Accepter la licence Xcode:"
echo "   sudo xcodebuild -license accept"
echo ""
echo "3. Vérifier la configuration:"
echo "   xcode-select -p"
echo ""
echo "Vous devriez voir: /Applications/Xcode.app/Contents/Developer"
