#!/bin/bash
echo "📦 Résolution des Packages Google Maps"
echo ""
echo "Ce script va vous guider pour résoudre les packages manquants."
echo ""
echo "📋 Étapes à suivre dans Xcode:"
echo ""
echo "1. File > Packages > Reset Package Caches"
echo "2. File > Packages > Resolve Package Versions"
echo "3. Attendez que les packages soient résolus"
echo "4. Vérifiez dans Package Dependencies que vous voyez:"
echo "   - ios-maps-sdk"
echo "   - ios-places-sdk"
echo "5. Target > General > Frameworks, Libraries, and Embedded Content"
echo "   - Vérifiez que GoogleMaps et GooglePlaces sont présents"
echo ""
echo "🔧 Si les packages ne sont pas présents, ajoutez-les:"
echo "   File > Add Package Dependencies..."
echo "   URL: https://github.com/googlemaps/ios-maps-sdk"
echo "   URL: https://github.com/googlemaps/ios-places-sdk"
